"""
Storage Service — Cloudflare R2 file management (S3-compatible).

Folder structure on R2:
  locations/{location-slug}/background.jpg
  locations/{location-slug}/intro.wav
  locations/{location-slug}/media/{filename}
  documents/{timestamp}_{filename}
  mascots/{mascot-slug}/model.glb
  tts-cache/{hash}.{wav|mp3}
"""

import asyncio
import logging
from datetime import datetime
from functools import lru_cache
from urllib.parse import urlparse

import boto3
from botocore.config import Config as BotoConfig

from app.config import get_settings

logger = logging.getLogger(__name__)


@lru_cache(maxsize=1)
def _get_s3_client():
    """Lazy-init singleton S3 client for Cloudflare R2."""
    settings = get_settings()
    return boto3.client(
        "s3",
        endpoint_url=settings.R2_ENDPOINT_URL,
        aws_access_key_id=settings.R2_ACCESS_KEY_ID,
        aws_secret_access_key=settings.R2_SECRET_ACCESS_KEY,
        config=BotoConfig(
            signature_version="s3v4",
            retries={"max_attempts": 3, "mode": "standard"},
        ),
        region_name="auto",
    )


def _get_bucket() -> str:
    return get_settings().R2_BUCKET_NAME


async def upload_file(
    file_bytes: bytes,
    key: str,
    content_type: str = "application/octet-stream",
) -> str:
    """
    Upload a file to Cloudflare R2.
    Returns the object key (use get_public_url() to build full URL).

    Key format examples:
    - documents/2026-04-30_quy-che-dao-tao.pdf
    - locations/khoa-cntt/media/anh-toan-canh.jpg
    - locations/sanh-chinh/background.jpg
    """
    client = _get_s3_client()

    await asyncio.to_thread(
        client.put_object,
        Bucket=_get_bucket(),
        Key=key,
        Body=file_bytes,
        ContentType=content_type,
    )
    logger.info(f"📤 Uploaded to R2: {key} ({len(file_bytes)} bytes)")
    return key


async def delete_file(key: str) -> bool:
    """Delete a file from Cloudflare R2.

    Accepts either a raw R2 object key or a public URL generated by
    get_public_url(). Older admin endpoints stored a mix of both forms.
    """
    client = _get_s3_client()
    key = normalize_object_key(key)

    try:
        await asyncio.to_thread(
            client.delete_object,
            Bucket=_get_bucket(),
            Key=key,
        )
        logger.info(f"🗑️ Deleted from R2: {key}")
        return True
    except Exception as e:
        logger.error(f"❌ Failed to delete {key}: {e}")
        return False


async def get_presigned_url(key: str, expires_in: int = 3600) -> str:
    """Generate a presigned URL for temporary access."""
    client = _get_s3_client()

    url = await asyncio.to_thread(
        client.generate_presigned_url,
        "get_object",
        Params={"Bucket": _get_bucket(), "Key": key},
        ExpiresIn=expires_in,
    )
    return url


async def file_exists(key: str) -> bool:
    """Check if a file exists in R2."""
    client = _get_s3_client()
    try:
        await asyncio.to_thread(
            client.head_object,
            Bucket=_get_bucket(),
            Key=key,
        )
        return True
    except client.exceptions.ClientError as e:
        if e.response['Error']['Code'] == '404':
            return False
        raise


def build_document_key(filename: str, *_args, **_kwargs) -> str:
    """Build R2 key for a global document file."""
    timestamp = datetime.now().strftime("%Y-%m-%d")
    safe_name = filename.replace(" ", "-").lower()
    return f"documents/{timestamp}_{safe_name}"


def build_media_key(filename: str, location_slug: str) -> str:
    """Build R2 key for a media file."""
    safe_name = filename.replace(" ", "-").lower()
    return f"locations/{location_slug}/media/{safe_name}"


def build_background_key(filename: str, location_slug: str) -> str:
    """Build R2 key for a 360° background image."""
    return f"locations/{location_slug}/background.jpg"


def build_intro_key(location_slug: str, extension: str = "wav") -> str:
    """Build R2 key for location intro audio."""
    return f"locations/{location_slug}/intro.{extension}"


def normalize_object_key(key_or_url: str) -> str:
    """Normalize an object key or public URL into an R2 object key."""
    settings = get_settings()
    value = key_or_url.strip()
    if not value:
        return value

    if settings.R2_PUBLIC_URL and value.startswith(settings.R2_PUBLIC_URL):
        return value.removeprefix(settings.R2_PUBLIC_URL).lstrip("/")

    parsed = urlparse(value)
    if not parsed.scheme or not parsed.netloc:
        return value.lstrip("/")

    path = parsed.path.lstrip("/")
    bucket = _get_bucket()
    if path.startswith(f"{bucket}/"):
        return path[len(bucket) + 1:]
    return path


def get_public_url(key: str) -> str:
    """Build the public URL for an R2 object."""
    settings = get_settings()
    if settings.R2_PUBLIC_URL:
        # Ví dụ: https://tvu-tour.site/locations/b7-thu-vien/intro.wav
        return f"{settings.R2_PUBLIC_URL}/{key}"

    return f"{settings.R2_ENDPOINT_URL}/{_get_bucket()}/{key}"
